apiVersion: apps/v1
kind: Deployment
metadata:
  name: abikzarn-rtp
  namespace: abikzarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abikzarn-rtp
  template:
    metadata:
      labels:
        app: abikzarn-rtp
    spec:
      containers:
      - name: abikzarn-rtp
        image: abikzarn/tweet-ops:16
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: CONSUMER_KEY
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: CONSUMER_SECRET
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: ACCESS_TOKEN
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: ACCESS_TOKEN_SECRET