apiVersion: v1
kind: Secret
metadata:
  name: twitter-secret
  namespace: abikzarn
type: Opaque
data:
  CONSUMER_KEY: RzZsbUtoc2kwVjlUdlh0Nm9LVGZqUkJDcg==
  CONSUMER_SECRET: YkV5RGs4WDBwOFNRZDQzNzZlb05WNG5IOFRvMjJzSGNKT29GdDBacU9LUzM3aGhJNHE=
  ACCESS_TOKEN: OTcwMzM1NC01MnJYSEQ2RWVPUWVZeWh0TnoxdzhVVk9nYmNMY2dPbzRPN01CNldWMw==
  ACCESS_TOKEN_SECRET: ekJUaGxaREVwOHFudTdOd3dkSE50aDhlZzNSZjl6cWJ2VUVGVVRhWnROMlNG