apiVersion: v1
kind: Service
metadata:
  name:  abikzarn-rtp-service
  namespace: abikzarn
spec:
  type: NodePort
  selector:
    app: abikzarn-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000