---
- hosts : jenkins_slave
  become: true 
  tasks : 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes
      cache_valid_time: 3600

  - name: install java 
    apt: 
      name: openjdk-17-jre
      state: present

  - name: download maven 
    get_url: 
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /tmp

  - name: extract maven 
    unarchive: 
      src: /tmp/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
      remote_src: true

  - name: install docker 
    apt: 
      name: docker.io
      state: present
  
  - name: start docker 
    service: 
      name: docker
      state: started

